#!/bin/sh

BACKUP_FOLDER=/opt/mysql/backup
NOW=$(date '+%Y-%m-%d_%H-%M')

GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)
AZCLI=$(which azure)

[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER

FILE=${BACKUP_FOLDER}/${BLOB_NAME}-${NOW}.sql.gz
$MYSQLDUMP -h $MYSQL_CONTAINER_NAME -u $MYSQL_USER -p${MYSQL_PASSWORD} --databases $MYSQL_DATABASE | $GZIP -9 > $FILE
$AZCLI storage blob upload $FILE $CONTAINER -c "DefaultEndpointsProtocol=https;BlobEndpoint=https://$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/;AccountName=$AZURE_STORAGE_ACCOUNT;AccountKey=$AZURE_STORAGE_ACCESS_KEY"

rm -f $FILE